name: ecostore
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  carousel_slider: ^4.2.1
  sizer: ^2.0.15
  ionicons: ^0.2.2
  font_awesome_flutter: ^10.5.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_messaging: ^14.6.9
  cloud_firestore: ^4.9.3
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/men1.jpg
    - images/men2.jpg
    - images/tech1.jpg
    - images/tech2.jpg
    - images/women1.jpg
    - images/mobile1.jpg
    - images/headset1.jpg
    - images/mensclothing1.jpg
    - images/womensclothing1.jpg
    - images/mobile2.jpg
    - images/luxurybag1.jpg
    - images/jacket1.jpg
    - images/laptopsale1.jpg
    - images/pages/screen1.png

  fonts:
    - family: Quicksand-Regular
      fonts:
        - asset: fonts/Quicksand/static/Quicksand-Regular.ttf
    - family: Quicksand-SemiBold
      fonts:
        - asset: fonts/Quicksand/static/Quicksand-SemiBold.ttf
    - family: Quicksand-Medium
      fonts:
        - asset: fonts/Quicksand/static/Quicksand-Medium.ttf
    - family: Quicksand-Bold
      fonts:
        - asset: fonts/Quicksand/static/Quicksand-Bold.ttf
    

    
